// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_foundation_of_the_foundations = "CgkIsPDl6P8HEAIQAg"; // <GPGSID>
        public const string achievement_real_knight = "CgkIsPDl6P8HEAIQAw"; // <GPGSID>
        public const string achievement_richer_than_midas = "CgkIsPDl6P8HEAIQBQ"; // <GPGSID>
        public const string achievement_how_did_you_find_it = "CgkIsPDl6P8HEAIQBg"; // <GPGSID>
        public const string leaderboard_best_runners = "CgkIsPDl6P8HEAIQAQ"; // <GPGSID>
        public const string achievement_demonic_runner = "CgkIsPDl6P8HEAIQBA"; // <GPGSID>

}

